// Catálogo de giros (MCC) con pisos comerciales Payefy+Broxel.
// Generado desde MCC_Tasas_Payefy_Broxel.xlsx — columnas "Piso Comercial (Broxel + 0.30%)".
// Los pisos ya incluyen los 0.30 pts de margen base; no vender por debajo de estos valores.

export interface GiroMcc {
  mcc: string
  familia: string
  descripcion: string
  pisoDebito: number  // % sin IVA
  pisoCredito: number // % sin IVA
}

/** Margen base de Payefy, ya incluido en los pisos del Excel. */
export const BASE_MARKUP = 0.3

/** Lo que cuestan de contrato (costo, NO precio de venta). */
export const AMEX_CONTRACT_COST = 2.8
export const INTERNATIONAL_CONTRACT_COST = 3.3

// Se les suma el mismo margen que ya traen los giros del Excel: si se
// vendieran al costo, AMEX e Internacional saldrían sin margen mientras
// todos los demás giros lo llevan.
// Redondeo a 2 decimales: en coma flotante 2.8 + 0.3 = 3.0999999999999996,
// que se colaría tal cual a la propuesta y a las comparaciones de piso.
const conMargen = (costo: number) => Math.round((costo + BASE_MARKUP) * 100) / 100

export const AMEX_FLOOR_RATE = conMargen(AMEX_CONTRACT_COST)                   // 3.1 %
export const INTERNATIONAL_FLOOR_RATE = conMargen(INTERNATIONAL_CONTRACT_COST) // 3.6 %

export const MCC_CATALOG: GiroMcc[] = [
  { mcc: "4722", familia: "Agencias de Viajes", descripcion: "AGENCIAS DE VIAJES, OPERADORAS DE VIAJES", pisoDebito: 1.7, pisoCredito: 2.18 },
  { mcc: "5399", familia: "Agregador", descripcion: "Agregador de Comercios o Facilitador de Pagos", pisoDebito: 1.75, pisoCredito: 2.36 },
  { mcc: "5960", familia: "Aseguradoras", descripcion: "MERCADEO DIRECTO – SERVICIOS DE SEGUROS", pisoDebito: 1.75, pisoCredito: 2.14 },
  { mcc: "6300", familia: "Aseguradoras", descripcion: "ASEGURADORAS - VENTAS DE SEGUROS, POLIZAS", pisoDebito: 1.75, pisoCredito: 2.14 },
  { mcc: "8398", familia: "Beneficencia", descripcion: "ORGANIZACIONES DE SERVICIO SOCIAL, (ORGANIZACIONES DE BENEFICENCIA)", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "7911", familia: "Colegios y Universidades", descripcion: "BAILE - SALONES Y ESCUELAS DE BAILE", pisoDebito: 1.35, pisoCredito: 1.72 },
  { mcc: "8220", familia: "Colegios y Universidades", descripcion: "UNIVERSIDADES, (COLEGIOS Y PREPARATORIAS), (ESCUELAS PROFESIONALES), POSGRADO", pisoDebito: 1.35, pisoCredito: 1.72 },
  { mcc: "8244", familia: "Colegios y Universidades", descripcion: "ESCUELAS - ADMINISTRACION, (ESCUELAS - COMERCIALES Y SECRETARIALES), (ESCUELAS SECRETARIALES)", pisoDebito: 1.35, pisoCredito: 1.72 },
  { mcc: "8249", familia: "Colegios y Universidades", descripcion: "ESCUELAS - PROFESIONALES, (PROFESIONAL), ESCUELAS DE OFICIOS", pisoDebito: 1.35, pisoCredito: 1.72 },
  { mcc: "5814", familia: "Comida Rápida", descripcion: "COMERCIO QUE VENDE COMIDA PREPARADA PARA CONSUMO INMEDIATO EN SUS INSTALACIONES O PARA LLEVAR. RESTAURANTES DE COMIDA RÁPIDA PUEDEN TENER O NO VENTANILLAS PARA ORDENAR Y RECOGER LA COMIDA EN AUTOMÓVIL Y PUEDEN O NO PROPORCIONAR EL SERVICIO DE MESEROS PARA LLEVAR LA COMIDA A LA MESA. EN CUALQUIERA DE LOS CASOS, EL PEDIDO ES PAGADO EN EL MOSTRADOR, O EN LA VENTANILLA DE ACCESO DEL AUTOMÓVIL Y SE SIRVEN DE FORMA PREPONDERANTE LOS SIGUIENTES PRODUCTOS ALIMENTICIOS: HAMBURGUESAS / HOT DOGS, PIZZAS, TACOS / TORTAS / QUESADILLAS, SÁNDWICHES / BAGUETTES, TAMALES, POLLO FRITO EMPANIZADO, DONAS, CAFÉ / TÉ, HELADOS.", pisoDebito: 1.35, pisoCredito: 1.77 },
  { mcc: "8211", familia: "Educación Básica", descripcion: "ESCUELAS - SECUNDARIAS, (ESCUELAS - PRIMARIAS), (ESCUELAS PRIMARIAS Y SECUNDARIAS)", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "8241", familia: "Educación Básica", descripcion: "ESCUELAS - CURSOS POR CORRESPONDENCIA", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "8299", familia: "Educación Básica", descripcion: "ESCUELAS Y ACADEMIAS - NO CLASIFICADAS, (SERVICIOS EDUCATIVOS - NO CLASIFICADAS)", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "4411", familia: "Entretenimiento", descripcion: "LINEAS DE CRUCEROS, (BARCOS DE VAPOR)", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "4899", familia: "Entretenimiento", descripcion: "PAGO DE SERVICIO POR TELEVISION CABLE/POR EVENTO", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7032", familia: "Entretenimiento", descripcion: "CAMPAMENTOS - NIÑOS,(CAMPAMENTO - JOVENES), (CAMPAMENTOS NIÑOS, NIÑAS)", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7519", familia: "Entretenimiento", descripcion: "RENTA - CASAS RODANTES, (RENTA – VEHICULOS RECREATIVOS, EXCURSIONES),", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7832", familia: "Entretenimiento", descripcion: "CINES, TEATROS", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7841", familia: "Entretenimiento", descripcion: "RENTA DE VIDEOS, (VIDEOS)", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7922", familia: "Entretenimiento", descripcion: "TEATROS Y CINES", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7932", familia: "Entretenimiento", descripcion: "BILLARRES", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7933", familia: "Entretenimiento", descripcion: "BOLICHES", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7941", familia: "Entretenimiento", descripcion: "CLUBES DEPORTIVOS PROFESIONALES, (HIPODROMOS, AUTODROMOS, GALGODROMOS),(ESTADIOS DEPORTIVOS),(CAMPOS DE ATLETISMO),(DEPORTES - PROMOTORES Y PROFESIONAL", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7992", familia: "Entretenimiento", descripcion: "CAMPOS DE GOLF - PUBLICO", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7994", familia: "Entretenimiento", descripcion: "VIDEO JUEGOS - ESTABLECIMIENTOS", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7996", familia: "Entretenimiento", descripcion: "ADIVINOS, LECTURA DE CARTAS, (CIRCOS),(PARQUES DE DIVERSION),(FERIAS)", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7997", familia: "Entretenimiento", descripcion: "CLUBS DEPORTIVOS - MEMBRESIAS,(CURSOS PRIVADOS DE GOLF),(CLUBS DE TENIS - MEMBRESIAS),(CLUBS - MEMBRESIAS (ATLETICOS, DEPORTIVOS, DIVERSION),(CAMPO D", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7998", familia: "Entretenimiento", descripcion: "ACUARIOS, ESPECTACULOS MARINOS", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7999", familia: "Entretenimiento", descripcion: "JARDINES BOTANICOS,(CAMPOS DE SKI),(INSTRUCTORES DE DEPORTES),(ZOOLOGICOS),(GOLFITO Y GO-KARS),(SERVICIOS DE ENTRETENIMIENTO Y DE DIVERSION),(INSTRUCT", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "7523", familia: "Estacionamientos", descripcion: "ESTACIONAMIENTOS/PENSIONES", pisoDebito: 1.6, pisoCredito: 1.72 },
  { mcc: "5912", familia: "Farmacias", descripcion: "DROGUERIAS, (FARMACIAS)", pisoDebito: 1.6, pisoCredito: 1.88 },
  { mcc: "5541", familia: "Gasolineras", descripcion: "ESTACIONES DE SERVICIO, GASOLINERIAS, ESTACIONES DE SERVICIO PARA TODO TIPO DE TRANSPORTE (CON O SIN SERVICIOS AUXILIARES)", pisoDebito: 1.05, pisoCredito: 1.6 },
  { mcc: "5542", familia: "Gasolineras", descripcion: "DISPENSADOR AUTOMATICO DE GASOLINA", pisoDebito: 1.05, pisoCredito: 1.6 },
  { mcc: "4900", familia: "Gobierno", descripcion: "SERVICIOS GUBERNAMENTALES, AGUA, ELECTRICIDAD, \n SANITARIOS, PREDIAL, TENENCIA, IMPUESTOS Y DERECHOS", pisoDebito: 1.35, pisoCredito: 1.63 },
  { mcc: "9211", familia: "Gobierno", descripcion: "PENSIONES ALIMENTICIAS,(COSTOS DE JUICIOS)", pisoDebito: 1.35, pisoCredito: 1.63 },
  { mcc: "9222", familia: "Gobierno", descripcion: "MULTAS", pisoDebito: 1.35, pisoCredito: 1.63 },
  { mcc: "9311", familia: "Gobierno", descripcion: "PAGOS DE IMPUESTOS", pisoDebito: 1.35, pisoCredito: 1.63 },
  { mcc: "9399", familia: "Gobierno", descripcion: "OTROS PAGOS DE SERVICIOS - NO CLASIFICADOS, (BOMBEROS),(PAGOS DE SERVICIOS - DEPARTAMENTO DISTRITO FEDERAL), (PAGOS DE SERVICIOS - TESORERIA),", pisoDebito: 1.35, pisoCredito: 1.63 },
  { mcc: "9402", familia: "Gobierno", descripcion: "SERVICIOS POSTALES - SOLO GOBIERNO", pisoDebito: 1.35, pisoCredito: 1.63 },
  { mcc: "9950", familia: "Gobierno", descripcion: "COMPRAS INTERGUBERNAMENTALES", pisoDebito: 1.35, pisoCredito: 1.63 },
  { mcc: "8351", familia: "Guarderías", descripcion: "GUARDERIAS (PUERICULTURA),(SERVICIOS DE - CUIDADO POR DIA)", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "8062", familia: "Hospitales", descripcion: "HOSPITALES Y CLINICAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7011", familia: "Hoteles", descripcion: "SERVICIOS NO CLASIFICADOS - HOTELES, MOTELES, CENTROS TURISTICOS", pisoDebito: 1.7, pisoCredito: 2.18 },
  { mcc: "7012", familia: "Hoteles", descripcion: "TIEMPO COMPARTIDO", pisoDebito: 1.7, pisoCredito: 2.18 },
  { mcc: "742", familia: "Médicos y dentistas", descripcion: "SERVICIOS VETERINARIOS", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "8011", familia: "Médicos y dentistas", descripcion: "DOCTORES, OTRAS ESPECIALIDADES,(MEDICOS)", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "8021", familia: "Médicos y dentistas", descripcion: "ORTODONCISTAS, (DENTISTAS)", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "8031", familia: "Médicos y dentistas", descripcion: "OSTEOPATAS", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "8041", familia: "Médicos y dentistas", descripcion: "QUIROPRACTICOS", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "8042", familia: "Médicos y dentistas", descripcion: "OPTOMETRISTAS, (OFTALMOLOGOS)", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "8049", familia: "Médicos y dentistas", descripcion: "PEDICURISTAS,(QUIROPEDISTAS)", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "5422", familia: "Misceláneas", descripcion: "ABARROTES, MISCELANEAS, TIENDAS NATURISTAS, CARNICERIAS, PESCADERIAS, VERDULERIAS", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "780", familia: "Otros", descripcion: "SERVICIOS DE HORTICULTURA Y DE JARDINERIA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "1520", familia: "Otros", descripcion: "CONTRATISTAS EN GENERAL- RESIDENCIAL Y COMERCIAL", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "1711", familia: "Otros", descripcion: "CONTRATISTAS ( CALEFACCION VENTAS, SERVICIO E INSTALACION)\n (AIRE ACONDICIONADO, VENTAS E INSTALACION) (PLOMERIA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "1731", familia: "Otros", descripcion: "CONTRATISTAS ELECTRICISTAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "1740", familia: "Otros", descripcion: "CONTRATISTAS (YESO) (CANTERA Y MAMPOSTERIA) (TEJAS, PISOS Y AZULEJOS)\n (MAMPOSTERIA Y CANTERIA) (AISLAMIENTO)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "1750", familia: "Otros", descripcion: "CONTRATISTAS CARPINTERIA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "1761", familia: "Otros", descripcion: "CONTRATISTAS TECHOS, ESTRUCTURAS Y LAMINAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "1771", familia: "Otros", descripcion: "CONTRATISTAS CONSTRUCTORAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "1799", familia: "Otros", descripcion: "CONTRATISTAS (DEMOLICIONES) (PERFORACION) (CRISTALES) (DECORACION) \n (NO CLASIFICADOS) (TAPICEROS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "2741", familia: "Otros", descripcion: "PUBLICACIONES E IMPRESIONES EN GENERAL", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "2791", familia: "Otros", descripcion: "TIPOGRAFIAS, PLACAS, TRABAJOS SIMILARES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "2842", familia: "Otros", descripcion: "LIMPIEZA ESPECIALIZADA, PULIDOS, Y SERVICIOS SANITARIOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4111", familia: "Otros", descripcion: "TRANSBORDADORES, (TRANSPORTE LOCAL), (TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS, INCLUYENDO TRANSBORDADORES )", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4119", familia: "Otros", descripcion: "SERVICIOS DE AMBULANCIA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4214", familia: "Otros", descripcion: "COMPAÑIAS DE - MUDANZAS Y ALMACENAJE , (FLETES – MAQUINARIA PESADA), (CONTENEDORES DE CARGA LOCAL Y FORANEOS), (ENTREGA DE PAQUETERIA - LOCAL), (FLETE", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4215", familia: "Otros", descripcion: "TRASLADOS - FLETES, (SERVICIOS DE MENSAJERIA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4225", familia: "Otros", descripcion: "ALMACENES, DEPOSITOS, (BODEGAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4457", familia: "Otros", descripcion: "RENTA/ARRENDAMIENTO - YATES Y LANCHAS, (RENTA - YATES, LANCHAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4468", familia: "Otros", descripcion: "SERVICIO/ACCESORIOS – MARITIMOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4816", familia: "Otros", descripcion: "COMERCIOS ELECTRONICOS (VENTAS A TRAVES DE INTERNET), (SERVICIOS - RED DE COMPUTADORAS), (SERVICIOS DE INFORMACION POR COMPUTADORA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4829", familia: "Otros", descripcion: "GIROS BANCARIOS/POSTALES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5051", familia: "Otros", descripcion: "CENTROS DE SERVICIO PARA EQUIPOS DE OFICINA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5122", familia: "Otros", descripcion: "MEDICINAS, MEDICINAS DE PATENTE, FARMACOS DIVERSOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5172", familia: "Otros", descripcion: "PETROLEO Y PRODUCTOS DERIVADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5962", familia: "Otros", descripcion: "MERCADO DIRECTO - SERVICIOS RELACIONADOS CON VIAJES Y ARREGLOS RELACIONADOS A (EXCLUYENDO LAS AGENCIAS DE VIAJES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5964", familia: "Otros", descripcion: "MERCADO DIRECTO - VENTAS POR CATALOGO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5966", familia: "Otros", descripcion: "MERCADEO DIRECTO - COMERCIANTES DE TELEMERCADEO QUE HACEN LLAMADAS A LOS TARJETAHABIENTES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5967", familia: "Otros", descripcion: "MERCADEO DIRECTO - COMERCIANTES QUE PRESTAN SERVICIOS POR\n TELEFONO Y QUE RECIBEN LLAMADAS DE LOS TARJETAHABIENTES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5968", familia: "Otros", descripcion: "[DESHABILITADO]MERCADEO DIRECTO - SUBSCRIPCION / CARGO AUTOMATICO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5969", familia: "Otros", descripcion: "MERCADEO DIRECTO - NO CLASIFICADO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "6010", familia: "Otros", descripcion: "BANCOS - DISPOSICIONES DE EFECTIVO EN VENTANILLA,(INSTITUCIONES FINANCIERAS - DISPOSICIONES DE EFECTIVO EN VENTANILLA),(AUTOFINANCIAMIENTOS - DISPOSI", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "6011", familia: "Otros", descripcion: "BANCOS - DISPOSICIONES AUTOMATICAS DE EFECTIVO, (AUTOFINANCIAMIENTOS DISPOSICIONES AUTOMATICAS DE EFECTIVO), (UNIONES DE CREDITO DISPOSICIONES A", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "6012", familia: "Otros", descripcion: "AUTOFINANCIAMIENTOS - SERVICIOS FINANCIEROS,(BANCOS - SERVICIOS FINANCIEROS),(UNIONES DE CREDITO - SERVICIOS FINANCIEROS), (INSTITUCIONES FINANCIERAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "6051", familia: "Otros", descripcion: "ORDENES DE PAGO, INSTITUCIONES NO FINANCIERAS (NO\n CABLEGRAFICAS), (INSTITUCIONES NO FINANCIERAS, CASAS DE CAMBIO, ORDENES DE PAGO(NO CABLEGRAFICAS), CH", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "6211", familia: "Otros", descripcion: "AGENTES - TRANSACCIONES DE BOLSA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7033", familia: "Otros", descripcion: "TRAILER PARKS,(CAMPAMENTOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7210", familia: "Otros", descripcion: "SERVICIOS - LAVANDERIA,(SERVICIO - LIMPIEZA Y LAVANDERIA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7211", familia: "Otros", descripcion: "SERVICIO - PAÑALES, (LAVANDERIAS AUTOMATICAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7261", familia: "Otros", descripcion: "SERVICIOS - FUNERARIOS, (CREMATORIOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7273", familia: "Otros", descripcion: "EDECANES, (DAMAS DE COMPAÑÍA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7276", familia: "Otros", descripcion: "CONTADORES - PREPARACION DE DECLARACION DE IMPUESTOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7277", familia: "Otros", descripcion: "ASESOR - FINANCIERO, (CONSEJEROS Y ASESORES PERSONALES PRESTAMOS, MATRIMONIAL, PERSONAL), (ASESORES - FINANCIEROS), (CONSEJERO - MATRIMONIAL)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7278", familia: "Otros", descripcion: "ASESORIAS - COMPRA/VENTA BIENES INMUEBLES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7297", familia: "Otros", descripcion: "SALONES - MASAJES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7298", familia: "Otros", descripcion: "CLINICAS - BELLEZA, (CLINICA - SALUD),(CLINICA - SALUD Y BELLEZA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7299", familia: "Otros", descripcion: "RENTA - DEPARTAMENTOS, EDIFICIO DE DEPARTAMENTOS, (OTROS SERVICIOS PERSONALES - NO CLASIFICADOS),(ADMINISTRADORES - BIENES RAICES, CORREDORES DE BOLSA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7311", familia: "Otros", descripcion: "SERVICIOS - PUBLICITARIOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7321", familia: "Otros", descripcion: "BUROS DE CREDITO, (BURO DE CREDITO AL CONSUMIDOR)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7333", familia: "Otros", descripcion: "FOTOGRAFIA, ARTE Y ANUNCIOS - COMERCIALES, (ARTES Y ANUNCIOS COMERCIALES), (ANUNCIOS FOTOGRAFICOS COMERCIALES, ARTE Y GRAFICA), (ANUNCIOS - COMERCIALES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7338", familia: "Otros", descripcion: "SERVICIO DE FOTOCOPIADO, REPRODUCCIONES Y ANTEPROYECTOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7339", familia: "Otros", descripcion: "SERVICIOS SECRETARIALES Y ESTENOGRAFICOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7342", familia: "Otros", descripcion: "SERVICIOS - FUMIGACION, (SERVICIOS - EXTERMINIO DE PLAGAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7349", familia: "Otros", descripcion: "SERVICIOS DE CONSERJERIA, LIMPIEZA Y MANTENIMIENTO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7361", familia: "Otros", descripcion: "AGENCIAS DE EMPLEOS, (SERVICIOS - EVENTOS ESPECIALES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7372", familia: "Otros", descripcion: "SERVICIO DE PROCESAMIENTO DE DATOS, (PROGRAMACION, DISEÑO INTEGRAL DE SISTEMAS, SERVICIOS DE PROCESAMIENTO DE DATOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7375", familia: "Otros", descripcion: "SERVICIOS DE CONSULTA/ENCUESTAS DE INFORMACION", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7379", familia: "Otros", descripcion: "MANTENIMIENTO, REPARACION DE COMPUTADORAS - SERVICIOS NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7392", familia: "Otros", descripcion: "SERVICIOS - RELACIONES PUBLICAS, (SERVICIOS - CONSULTORIA Y ADMINISTRACION),(SERVICIOS – CONSULTORIAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7393", familia: "Otros", descripcion: "GUARDIAS DE SEGURIDAD, (AGENCIAS – DETECTIVES PRIVADOS Y GUARDIAS DE SEGURIDAD),(PERROS GUARDIANES),(VEHICULOS BLINDADOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7395", familia: "Otros", descripcion: "LABORATORIOS FOTOGRAFICOS- REVELADO Y RETOQUE", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7399", familia: "Otros", descripcion: "OTROS SERVICIOS EMPRESARIALES - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7511", familia: "Otros", descripcion: "TRANSACCIONES - EN TRANSITO CARRETERO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7513", familia: "Otros", descripcion: "RENTA - CAMIONES, (RENTA – ACCESORIOS PARA REMOLQUES), (RENTA - CAMIONES Y REMOLQUES),(RENTA - REMOLQUES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7531", familia: "Otros", descripcion: "TALLERES - HOJALATERIA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7535", familia: "Otros", descripcion: "TALLERES - PINTURA DE AUTOS, (SERVICIO - PINTADO DE AUTOMOVILES),", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7542", familia: "Otros", descripcion: "SERVICIO - LAVADO DE AUTOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7549", familia: "Otros", descripcion: "SERVICIO - GRUAS Y TRASLADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7829", familia: "Otros", descripcion: "PRODUCCION Y DISTRIBUCION DE PELICULAS Y VIDEOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7929", familia: "Otros", descripcion: "BANDAS, ORQUESTAS, GRUPOS,DIVERSIONES - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7991", familia: "Otros", descripcion: "EXHIBICIONES Y ATRACCIONES TURISTICAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8043", familia: "Otros", descripcion: "OPTICAS, LENTES Y ANTEOJOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8050", familia: "Otros", descripcion: "SERVICIOS DE RECUPERACION, (SERVICIOS DE ENFERMERAS Y CUIDADO DE PERSONAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8071", familia: "Otros", descripcion: "LABORATORIOS DENTALES, (LABORATORIOS MEDICOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8099", familia: "Otros", descripcion: "SERVICIOS MEDICOS Y PARAMEDICOS - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8111", familia: "Otros", descripcion: "SERVICIOS LEGALES, (ABOGADOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8641", familia: "Otros", descripcion: "ASOCIACIONES - CIVICAS Y FRATERNIDADES, (ASOCIACIONES SOCIALES),(ASOCIACIONES - DE BENEFICIENCIA Y SERVICIO SOCIAL)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8651", familia: "Otros", descripcion: "ORGANIZACIONES - POLITICAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8661", familia: "Otros", descripcion: "ORGANIZACIONES - RELIGIOSAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8675", familia: "Otros", descripcion: "ASOCIACIONES - AUTOMOVILISTICAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8699", familia: "Otros", descripcion: "SINDICATOS, (ASOCIACIONES- NO CLASIFICADAS), (ASOCIACIONES PROFESIONALES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8734", familia: "Otros", descripcion: "LABORATORIOS DE PRUEBAS (NO MEDICOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8911", familia: "Otros", descripcion: "PROYECTOS INGENIERILES Y DE ARQUITECTURA, (PROYECTOS - INVESTIGACIO DE MERCADOS, ENCUESTAS),(PROYECTOS - ARQUITECTONICOS Y DE INGENIERIA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8931", familia: "Otros", descripcion: "SERVICIOS - CONTABILIDAD, (SERVICIOS - CONTABLES),(SERVICIOS - AUDITORIAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "8999", familia: "Otros", descripcion: "SERVICIOS PROFESIONALES - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "9223", familia: "Otros", descripcion: "PAGOS Y DEPOSITOS DE FIANZAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4784", familia: "Peaje", descripcion: "CUOTA - PUENTES, (CUOTAS Y TARIFAS - PUENTES Y CARRETERAS)", pisoDebito: 1.6, pisoCredito: 1.77 },
  { mcc: "5072", familia: "Refacciones y ferreterías", descripcion: "FERRETERIAS, ACCESORIOS Y EQUIPO", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "5074", familia: "Refacciones y ferreterías", descripcion: "EQUIPO - PLOMERIA Y CALEFACCION", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "5251", familia: "Refacciones y ferreterías", descripcion: "FERRETERIA", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "5533", familia: "Refacciones y ferreterías", descripcion: "AUTOPARTES, ACCESORIOS - AUTOMOTORES", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "7512", familia: "Renta de Autos", descripcion: "ARRENDADORAS DE AUTOS - NO CLASIFICADAS", pisoDebito: 1.7, pisoCredito: 2.18 },
  { mcc: "5812", familia: "Restaurantes", descripcion: "RESTAURANTES, (CAFETERIAS)", pisoDebito: 1.75, pisoCredito: 2.36 },
  { mcc: "5813", familia: "Restaurantes", descripcion: "BARES - BEBIDAS ALCOHOLICAS, (TABERNAS), (DISCOTECAS),(SALON DE COCKTALES),(CENTROS NOCTURNOS)", pisoDebito: 1.75, pisoCredito: 2.36 },
  { mcc: "7230", familia: "Salones de belleza", descripcion: "SALONES DE BELLEZA, (PELUQUERIAS), (ESTETICAS)", pisoDebito: 0.6, pisoCredito: 0.6 },
  { mcc: "5300", familia: "Supermercados", descripcion: "CLUBES DE MAYORISTAS", pisoDebito: 1.7, pisoCredito: 2.13 },
  { mcc: "5310", familia: "Supermercados", descripcion: "TIENDAS DE DESCUENTO", pisoDebito: 1.7, pisoCredito: 2.13 },
  { mcc: "5311", familia: "Supermercados", descripcion: "TIENDAS DEPARTAMENTALES", pisoDebito: 1.7, pisoCredito: 2.13 },
  { mcc: "5331", familia: "Supermercados", descripcion: "TIENDAS DE PARTICIPACION ESTATAL", pisoDebito: 1.7, pisoCredito: 2.13 },
  { mcc: "5411", familia: "Supermercados", descripcion: "AUTOSERVICIOS Y SUPERMERCADOS, ABARROTES EN GENERAL, ULTRAMARINOS", pisoDebito: 1.7, pisoCredito: 2.13 },
  { mcc: "4814", familia: "Telecomunicaciones", descripcion: "SERVICIOS DE TELECOMUNICACION INCLUYENDO, LLAMADAS TELEFONICAS LOCALES Y LARGA DISTANCIA, LLAMADAS CON TARJETAS DE CREDITO, TELEFONO CON LECTOR DE BAN", pisoDebito: 1.75, pisoCredito: 2.05 },
  { mcc: "4821", familia: "Telecomunicaciones", descripcion: "SERVICIOS – TELEGRAFO", pisoDebito: 1.75, pisoCredito: 2.05 },
  { mcc: "4511", familia: "Transporte Aéreo", descripcion: "OTRAS LINEAS AEREAS -FLETES AEREOS- NO CLASIFICADAS, (CARGA AEREA, LINEAS AEREAS - NO CLASIFICADOS)", pisoDebito: 1.35, pisoCredito: 2.11 },
  { mcc: "4582", familia: "Transporte Aéreo", descripcion: "AEROPUERTOS, TERMINALES AEREAS", pisoDebito: 1.35, pisoCredito: 2.11 },
  { mcc: "4789", familia: "Transporte Aéreo", descripcion: "SERVICIOS DE TRANSPORTE -NO CLASIFICADO", pisoDebito: 1.35, pisoCredito: 2.11 },
  { mcc: "4011", familia: "Transporte Terrestre de Pasajeros", descripcion: "FERROCARRILES", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "4112", familia: "Transporte Terrestre de Pasajeros", descripcion: "FERROCARRIL DE PASAJEROS", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "4121", familia: "Transporte Terrestre de Pasajeros", descripcion: "LIMOSINAS, (TAXIS)", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "4131", familia: "Transporte Terrestre de Pasajeros", descripcion: "AUTOBUSES FORANEOS", pisoDebito: 1.7, pisoCredito: 1.77 },
  { mcc: "763", familia: "Ventas al detalle (Retail)", descripcion: "COOPERATIVAS AGRICOLAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "4812", familia: "Ventas al detalle (Retail)", descripcion: "EQUIPOS DE TELECOMUNICACION INCLUYENDO VENTA DE TELEFONOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5013", familia: "Ventas al detalle (Retail)", descripcion: "VEHICULOS DE MOTOR, ACCESORIOS Y AUTO PARTES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5021", familia: "Ventas al detalle (Retail)", descripcion: "MUEBLES PARA - OFICINA Y COMERCIOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5039", familia: "Ventas al detalle (Retail)", descripcion: "MATERIALES PARA LA CONSTRUCCION - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5044", familia: "Ventas al detalle (Retail)", descripcion: "EQUIPOS DE - OFICINA, FOTOGRAFICO, FOTOCOPIADO Y MICROFILM", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5045", familia: "Ventas al detalle (Retail)", descripcion: "COMPUTADORAS - EQUIPO PERIFERICO DE COMPUTADORAS, SOFTWARE", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5046", familia: "Ventas al detalle (Retail)", descripcion: "EQUIPO COMERCIAL - NO CLASIFICADO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5047", familia: "Ventas al detalle (Retail)", descripcion: "EQUIPO Y SUMINISTROS - HOSPITALES,(EQUIPO Y SUMINISTROS -\n LABORATORIO),(EQUIPO Y SUMINISTROS OFTALMOLOGICOS), (EQUIPO Y SUMINISTROS - MEDICOS),(EQUIP", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5065", familia: "Ventas al detalle (Retail)", descripcion: "PARTES Y EQUIPO ELECTRICO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5085", familia: "Ventas al detalle (Retail)", descripcion: "ACCESORIOS INDUSTRIALES - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5094", familia: "Ventas al detalle (Retail)", descripcion: "METALES Y PIEDRAS PRECIOSAS, RELOJERIA Y JOYERIA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5099", familia: "Ventas al detalle (Retail)", descripcion: "BIENES DURADEROS - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5111", familia: "Ventas al detalle (Retail)", descripcion: "ARTICULOS DE ESCRITORIO, OFICINA Y PAPELERIA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5131", familia: "Ventas al detalle (Retail)", descripcion: "MERCERIAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5137", familia: "Ventas al detalle (Retail)", descripcion: "UNIFORMES - HOMBRES / MUJERES / NIÑOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5139", familia: "Ventas al detalle (Retail)", descripcion: "CALZADO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5169", familia: "Ventas al detalle (Retail)", descripcion: "PRODUCTOS QUIMICOS Y ALIACIONES - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5192", familia: "Ventas al detalle (Retail)", descripcion: "LIBROS, PERIODICOS Y REVISTAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5193", familia: "Ventas al detalle (Retail)", descripcion: "ACCESORIOS PARA FLORERIAS, FLORES E INVERNADEROS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5198", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDOR DE PINTURAS Y BARNICES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5199", familia: "Ventas al detalle (Retail)", descripcion: "PERECEDEROS - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5200", familia: "Ventas al detalle (Retail)", descripcion: "ALMACEN DE ELECTRODOMESTICOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5211", familia: "Ventas al detalle (Retail)", descripcion: "CIMBRAS / MADERERIAS, (MATERIALES PARA CONSTRUCCION)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5231", familia: "Ventas al detalle (Retail)", descripcion: "PAPEL TAPIZ, (PINTURAS Y PAPEL TAPIZ), (VIDRIERIAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5261", familia: "Ventas al detalle (Retail)", descripcion: "ACCESORIOS - JARDIN, (ACCESORIOS - JARDININERIA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5271", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES – CAMPERS Y REMOLQUES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5309", familia: "Ventas al detalle (Retail)", descripcion: "TIENDAS LIBRES DE IMPUESTO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5441", familia: "Ventas al detalle (Retail)", descripcion: "DULCERIAS, (PASTELERIAS Y CONFITERIAS), (SEMILLAS Y SIMILARES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5451", familia: "Ventas al detalle (Retail)", descripcion: "LECHERIAS, CREMERIAS, LACTEOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5462", familia: "Ventas al detalle (Retail)", descripcion: "PANADERIAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5499", familia: "Ventas al detalle (Retail)", descripcion: "TIENDAS DE CONVENIENCIA, MINISUPER", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5511", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES DE AUTOMOVILES (NUEVOS Y USADOS) - VENTA, ARRENDAMIENTO, SERVICIO, REPARACIONES, PARTES, (DISTRIBUIDORES DE CAMIONES (NUEVOS Y USADOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5521", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES DE AUTOMOVILES (SOLO USADOS), (DISTRIBUIDORES CAMIONES (SOLO USADOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5532", familia: "Ventas al detalle (Retail)", descripcion: "LLANTAS - AUTOMOTORES, DISTRIBUIDOR DE LLANTAS - AUTOMOTORES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5551", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES DE YATES, BARCOS, LANCHAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5561", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES DE CAMPERS, ( DISTRIBUIDOR DE ACCESORIOS PARA REMOLQUES), ( DISTRIBUIDOR DE REMOLQUES), (DISTRIBUIDORES DE REMOLQUES Y ACCESORIOS PARA A", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5571", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES Y AGENCIAS - MOTOCICLETAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5592", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES - CASAS RODANTES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5598", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES DE AUTOS PARA LA NIEVE", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5599", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES DE AUTOMOTORES EN GENERAL, AVIONES, TRACTORES - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5611", familia: "Ventas al detalle (Retail)", descripcion: "BOUTIQUE - ROPA PARA NIÑOS, (ROPA - CABALLEROS Y NIÑOS), (BOUTIQUE CABALLEROS Y NIÑOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5621", familia: "Ventas al detalle (Retail)", descripcion: "(ROPA CASUAL - DAMAS), (BOUTIQUES ROPA CASUAL - DAMAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5631", familia: "Ventas al detalle (Retail)", descripcion: "(BOUTIQUE ROPA - ESPECIAL), (BOUTIQUES - LENCERIAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5641", familia: "Ventas al detalle (Retail)", descripcion: "BOUTIQUES ROPA - NIÑOS Y BEBES, (ROPA - NIÑOS Y BEBES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5651", familia: "Ventas al detalle (Retail)", descripcion: "BOUTIQUES ROPA - PARA TODA LA FAMILIA, (ROPA PARA TODA LA FAMILIA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5655", familia: "Ventas al detalle (Retail)", descripcion: "ROPA - EQUITACION, (ROPA - DEPORTIVA), (ROPA - PARA DEPORTES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5661", familia: "Ventas al detalle (Retail)", descripcion: "ZAPATERIAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5681", familia: "Ventas al detalle (Retail)", descripcion: "PIELES FINAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5691", familia: "Ventas al detalle (Retail)", descripcion: "ROPA PARA CABALLEROS Y DAMAS, (BOUTIQUES - ROPA PARA CABALLEROS Y DAMAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5697", familia: "Ventas al detalle (Retail)", descripcion: "ALTA COSTURA - CABALLEROS Y DAMAS,(ALTA COSTURA - DAMAS),(SASTRES - DISEÑO Y COSTURA),(SASTRES Y ALTA COSTURA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5698", familia: "Ventas al detalle (Retail)", descripcion: "PELUCAS Y BISOÑES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5699", familia: "Ventas al detalle (Retail)", descripcion: "ROPA Y ACCESORIOS - MISCELANEOS, (ROPA - MISCELANEO)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5712", familia: "Ventas al detalle (Retail)", descripcion: "MOBILIARIO ESPECIAL PARA EL HOGAR - MISCELANEO, (VENTAS DE EQUIPO),(MUEBLES, MOBILIARIO PARA EL HOGAR Y EQUIPOS (EXCEPTO ELECTRODOMESTICOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5713", familia: "Ventas al detalle (Retail)", descripcion: "ALFOMBRAS Y TAPETES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5714", familia: "Ventas al detalle (Retail)", descripcion: "CORTINAS, CORTINEROS, (TAPICERIAS),", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5718", familia: "Ventas al detalle (Retail)", descripcion: "ACCESORIOS PARA CHIMENEAS, CHIMENEAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5719", familia: "Ventas al detalle (Retail)", descripcion: "EQUIPAMIENTO PARA EL HOGAR, EXCEPTO ELECTRODOMESTICOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5722", familia: "Ventas al detalle (Retail)", descripcion: "ACCESORIOS - ELECTRODOMESTICOS, (ELECTRODOMESTICOS - NO CLASIFICADOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5732", familia: "Ventas al detalle (Retail)", descripcion: "TIENDAS DE ELECTRONICA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5733", familia: "Ventas al detalle (Retail)", descripcion: "TIENDAS DE MUSICA - INSTRUMENTOS MUSICALES, PIANOS, PARTITURAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5734", familia: "Ventas al detalle (Retail)", descripcion: "TIENDAS DE SOFTWARE PARA COMPUTADORAS, (SOFTWARE - COMPUTADORAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5735", familia: "Ventas al detalle (Retail)", descripcion: "TIENDA DE DISCOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5811", familia: "Ventas al detalle (Retail)", descripcion: "ALIMENTOS - PROVEEDORES Y DISTRIBUIDORES", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5921", familia: "Ventas al detalle (Retail)", descripcion: "DEPOSITOS DE CERVEZAS, (VINATERIAS), (DEPOSITOS DE CERVEZAS, VINOS Y LICORES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5931", familia: "Ventas al detalle (Retail)", descripcion: "(TIENDAS DE ARTICULOS USADOS), (TIENDAS DE ARTICULOS DE SEGUNDA MANO)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5932", familia: "Ventas al detalle (Retail)", descripcion: "TIENDAS DE ANTIGÜEDADES, BAZARES - VENTA, REPARACION, RESTAURACION", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5933", familia: "Ventas al detalle (Retail)", descripcion: "CASAS DE EMPEÑO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5935", familia: "Ventas al detalle (Retail)", descripcion: "VENTAS DE SALDOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5937", familia: "Ventas al detalle (Retail)", descripcion: "REPRODUCCION DE ANTIGÜEDADES - VENTA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5940", familia: "Ventas al detalle (Retail)", descripcion: "BICICLETAS - VENTA Y REPARACION", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5941", familia: "Ventas al detalle (Retail)", descripcion: "DEPORTES Y ACCESORIOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5942", familia: "Ventas al detalle (Retail)", descripcion: "LIBRERIAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5943", familia: "Ventas al detalle (Retail)", descripcion: "ARTICULOS DE ESCRITORIO, (ARTICULOS DE OFICINA), (ARTICULOS ESCOLARES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5944", familia: "Ventas al detalle (Retail)", descripcion: "RELOJERIAS, (JOYERIAS), (PLATERIAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5945", familia: "Ventas al detalle (Retail)", descripcion: "JUEGOS DE MESA Y PASATIEMPOS, (JUGUETERIAS, JUGOS DE MESA Y PASATIEMPOS), (TIENDAS - JUEGOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5946", familia: "Ventas al detalle (Retail)", descripcion: "ARTICULOS Y ACCESORIOS FOTOGRAFICOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5947", familia: "Ventas al detalle (Retail)", descripcion: "TIENDAS DE REGALOS, (REGALOS Y ARTESANIAS),(TARJETAS),(NOVEDADES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5948", familia: "Ventas al detalle (Retail)", descripcion: "ARTICULO DE PIEL, (MALETAS Y EQUIPAJES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5949", familia: "Ventas al detalle (Retail)", descripcion: "TELAS Y CASIMIRES, (MERCERIAS),(BONETERIAS),(CORCETERIA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5950", familia: "Ventas al detalle (Retail)", descripcion: "CRISTALERIAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5963", familia: "Ventas al detalle (Retail)", descripcion: "VENTAS DE PUERTA - EN – PUERTA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5965", familia: "Ventas al detalle (Retail)", descripcion: "MERCADEO DIRECTO - TIENDAS AL MENUDEO QUE TAMBIEN VENDEN PORCATALOGO", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5970", familia: "Ventas al detalle (Retail)", descripcion: "ARTICULOS PARA LOS ARTISTAS, (ARTICULOS DE ARTE)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5971", familia: "Ventas al detalle (Retail)", descripcion: "GALERIAS DE ARTE,(DISTRIBUIDORES DE ARTE)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5972", familia: "Ventas al detalle (Retail)", descripcion: "COLECCION DE MONEDAS,(COLECCION DE ESTAMPILLAS),(TIENDAS DE NUMISMATICA),(FILATELIA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5973", familia: "Ventas al detalle (Retail)", descripcion: "ARTICULOS RELIGIOSOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5975", familia: "Ventas al detalle (Retail)", descripcion: "ARTICULOS PARA LA SORDERA - VENTAS, REPARACION Y ACCESORIOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5976", familia: "Ventas al detalle (Retail)", descripcion: "ARTICULO ORTOPEDICOS, PROTESIS - VENTA, REPARACION Y ACCESORIOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5977", familia: "Ventas al detalle (Retail)", descripcion: "TIENDAS - COSMETICOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5978", familia: "Ventas al detalle (Retail)", descripcion: "MAQUINAS DE ESCRIBIR - VENTAS, REPARACION, ACCESORIOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5983", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDOR DE GAS LICUADO, (DISTRIBUIDOR DE LEÑA), (DISTRIBUIDOR DE DIESEL, PETROLEO),(DISTRIBUIDOR DE - CARBON)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5992", familia: "Ventas al detalle (Retail)", descripcion: "FLORERIAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5993", familia: "Ventas al detalle (Retail)", descripcion: "TABAQUERIAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5994", familia: "Ventas al detalle (Retail)", descripcion: "PUESTOS DE PERIODICOS Y REVISTAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5995", familia: "Ventas al detalle (Retail)", descripcion: "TIENDAS DE MASCOTAS - ALIMENTO Y ACCESORIOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5996", familia: "Ventas al detalle (Retail)", descripcion: "VENTA, SERVICIO, ACCESORIOS - ALBERCAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5997", familia: "Ventas al detalle (Retail)", descripcion: "VENTAS, REPARACION - RAZURADORAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5998", familia: "Ventas al detalle (Retail)", descripcion: "VENTA DE TOLDOS, (VENTA DE TIENDAS DE CAMPAÑA)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "5999", familia: "Ventas al detalle (Retail)", descripcion: "DISTRIBUIDORES DE HIELO, (FUEGOS ARTIFICIALES), (TIENDAS DETALLISTAS - NO CLASIFICADAS),(LAPIDAS Y MONUMENTOS - VENTA E INSTALACION), (TROFEOS, VENTAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7216", familia: "Ventas al detalle (Retail)", descripcion: "TINTORERIAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7217", familia: "Ventas al detalle (Retail)", descripcion: "LIMPIEZA - TAPETES, (LIMPIEZA - ALFOMBRAS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7221", familia: "Ventas al detalle (Retail)", descripcion: "ESTUDIOS FOTOGRAFICOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7251", familia: "Ventas al detalle (Retail)", descripcion: "LIMPIEZA DE SOMBREROS, (REPARACION DE CALZADO Y BOLEROS),", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7296", familia: "Ventas al detalle (Retail)", descripcion: "RENTA - UNIFORMES, (RENTA - DISFRACES),(RENTA - SMOKINGS),(RENTA - ROPA,DISFRACES, UNIFORMES),(RENTA DE ROPA - FORMAL)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7394", familia: "Ventas al detalle (Retail)", descripcion: "RENTA - MUEBLES, (RENTA - DE HERRAMIENTAS, EQUIPO Y MUEBLES),(RENTAS DE EQUIPO),(RENTA Y ARRENDAMIENTO DE EQUIPOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7534", familia: "Ventas al detalle (Retail)", descripcion: "TALLERES - VULCANIZADORAS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7538", familia: "Ventas al detalle (Retail)", descripcion: "TALLERES - MECANICOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7622", familia: "Ventas al detalle (Retail)", descripcion: "TALLER DE REPARACION - APARATOS ELECTRONICOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7623", familia: "Ventas al detalle (Retail)", descripcion: "TALLER DE REPARACION - AIRE ACONDICIONADO, (TALLER DE REPARACION - REFRIGERACION/REFRIGERADORES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7629", familia: "Ventas al detalle (Retail)", descripcion: "TALLERES DE REPARACION - ELECTRICOS Y EQUIPOS PEQUEÑOS, (TALLER DE REPARACION - APARATOS ELECTRODOMESTICOS), (TALLER DE REPARACION - APARATOS ELECTRIC", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7631", familia: "Ventas al detalle (Retail)", descripcion: "TALLER DE REPARACION - RELOJES DE PULSO, (TALLER DE REPARACION JOYAS), (TALLER DE REPARACION - RELOJES)", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7641", familia: "Ventas al detalle (Retail)", descripcion: "RETAPIZADOS, (TALLER DE REPARACION - MUEBLES Y ACABADOS),", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7692", familia: "Ventas al detalle (Retail)", descripcion: "TALLER - SOLDADURA ELECTRICA Y AUTOGENA", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7699", familia: "Ventas al detalle (Retail)", descripcion: "TALLERES DE REPARACION MISCELANEOS - NO CLASIFICADOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7993", familia: "Ventas al detalle (Retail)", descripcion: "VENTA DE VIDEO JUEGOS, ACCESORIOS", pisoDebito: 1.75, pisoCredito: 2.13 },
  { mcc: "7995", familia: "Ventas al detalle (Retail)", descripcion: "CASINOS, CASAS DE JUEGO, (APUESTAS, INCLUYE BILLETES DE LOTERIA),(LOTERIAS, JUEGOS DE AZAR),(APUESTAS - CARRERAS DE CABALLOS)", pisoDebito: 1.75, pisoCredito: 2.13 },
]
